import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import { ThemeProvider } from '@/components/theme-provider'
import { SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'

const poppins = Poppins({
	variable: '--font-poppins',
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
})

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function asyncRootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${poppins.className} ${geistMono.variable} antialiased`}>
				<ThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange>
					<Navbar />
					<SidebarProvider>
						<AppSidebar />
						{/* <SidebarTrigger /> */}
						<div className="flex justify-center items-center w-full">{children}</div>
					</SidebarProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
